### ISSUE TITLE
Latest master breaks on fetching mim_nr?

### ISSUE THREAD

**Issue by dnil** [robinandeer/puzzle#19]
Thank you kindly! But I now have trouble looking at any variant instead? Lookup on mim_nr seems to fail? Sth wrong with that last new_omim_list? I did have a couple of build issues along the way, but they don't seem to be showstoppers.

```
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/puzzle/blueprints/variants/views.py", line 25, in variants
    thousand_g=thousand_g)
  File "/home/vagrant/.local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/vagrant/.local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/vagrant/.local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/vagrant/.local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/puzzle/blueprints/variants/templates/variants.html", line 2, in top-level template code
    {% from "macros/variant.html" import omim_links %}
  File "/vagrant/puzzle/templates/layouts/base.html", line 28, in top-level template code
    {% block body %}
  File "/vagrant/puzzle/templates/layouts/base.html", line 45, in block "body"
    {% block body_content %}{% endblock %}
  File "/vagrant/puzzle/blueprints/variants/templates/variants.html", line 29, in block "body_content"
    {% for variant in variants %}
  File "/vagrant/puzzle/plugins/vcf.py", line 233, in variants
    for variant_obj in filtered_variants:
  File "/vagrant/puzzle/plugins/vcf.py", line 206, in _variants
    self._add_genes(variant)
  File "/vagrant/puzzle/plugins/vcf.py", line 69, in _add_genes
    omim_number=get_omim_number(hgnc_id),
  File "/vagrant/puzzle/utils/get_info.py", line 65, in get_omim_number
    omim_number = HGNC_TO_OMIM.get(hgnc_symbol).get('mim_nr')
```

Also had a couple of issues during pip install (using otto dev) now compared to before:
```
 Running setup.py install for MarkupSafe
    
    building 'markupsafe._speedups' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c markupsafe/_speedups.c -o build/temp.linux-x86_64-2.7/markupsafe/_speedups.o
    markupsafe/_speedups.c:12:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Failure information, if any, is above.
    Retrying the build without the C extension now.
    
    
    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Plain-Python installation succeeded.
    ==========================================================================
```

Also, as before, during npm install:

```
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/opt/node-v4.1.0-linux-x64/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! path ../semver/bin/semver
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../semver/bin/semver' -> '/vagrant/node_modules/gulp/node_modules/.bin/semver'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
```

**Comment by moonso** [comment]
Closed by #20
