### ISSUE TITLE
File "cyvcf2/cyvcf2.pyx", line 155, in cyvcf2.cyvcf2.VCF.__init__ (cyvcf2/cyvcf2.c:7106) TypeError: Expected bytes, got path

### ISSUE THREAD

**Issue by J35P312** [robinandeer/puzzle#227]
Hello there!
Recently I installed the latest version of puzzle, it was installed without any apparent error, however when I run the test example I get the following error:

Traceback (most recent call last):
  File "/home/jesper/miniconda2/envs/test_puzzle/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/jesper/miniconda2/envs/test_puzzle/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jesper/Downloads/puzzle_test/puzzle/puzzle/__main__.py", line 19, in <module>
    sys.exit(cli())
  File "/home/jesper/miniconda2/envs/test_puzzle/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/jesper/miniconda2/envs/test_puzzle/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/jesper/miniconda2/envs/test_puzzle/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jesper/miniconda2/envs/test_puzzle/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jesper/miniconda2/envs/test_puzzle/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/jesper/miniconda2/envs/test_puzzle/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jesper/Downloads/puzzle_test/puzzle/puzzle/cli/view.py", line 107, in view
    variant_type = get_variant_type(file)
  File "/home/jesper/Downloads/puzzle_test/puzzle/puzzle/utils/get_file_info.py", line 48, in get_variant_type
    variants = VCF(variant_source)
  File "cyvcf2/cyvcf2.pyx", line 155, in cyvcf2.cyvcf2.VCF.__init__ (cyvcf2/cyvcf2.c:7106)
TypeError: Expected bytes, got path

Any ideas on how to fix it ?
Regards
Jesper

**Comment by moonso** [comment]
I'll have a look!

**Comment by moonso** [comment]
This seems to be a version problem with cyvcf2.
If you downgrade version to 0.2.8 it should work.
I've updated the requrements file

**Comment by J35P312** [comment]
Thanks, now it works perfectly!

**Comment by brentp** [comment]
Hi, I just happened to see this, could you try 0.4.0 (in bioconda)? And let me know how/if you can reproduce it there?

**Comment by colindaven** [comment]
I just got this error using a newer version of cyvcf2 if that helps, also with the test data (as per the tutorial https://robinandeer.gitbooks.io/puzzle/content/topics/tutorial.html )

pip list | grep cyvcf2
cyvcf2 (0.4.2)

Works fine after installing  0.2.8 as above

**Comment by brentp** [comment]
This error is because puzzle is sending a `path` object to cyvcf2 instead of string or bytes.
I suspect wrapping the call in str() would suffice.
