### ISSUE TITLE
path

### ISSUE THREAD

**Issue by colindaven** [robinandeer/puzzle#230]
Hi everybody,

I see in the requirements path.py is needed. I tried to install all of these, and downgraded cyvcf2 to version 0.2.8 I believe.

A version for path.py is not stated in the requirements.txt

I have 10.0, is this too high/low a version ?
`pip list  | grep path
path.py (10.0)`

puzzle view minimal.vcf 
Traceback (most recent call last):
  File "/usr/local/bin/puzzle", line 7, in <module>
    from puzzle.__main__ import cli
  File "/usr/local/lib/python2.7/dist-packages/puzzle/__main__.py", line 14, in <module>
    from puzzle.cli import base as cli
  File "/usr/local/lib/python2.7/dist-packages/puzzle/cli/__init__.py", line 5, in <module>
    from .init import init
  File "/usr/local/lib/python2.7/dist-packages/puzzle/cli/init.py", line 10, in <module>
    from puzzle.plugins import SqlStore
  File "/usr/local/lib/python2.7/dist-packages/puzzle/plugins/__init__.py", line 6, in <module>
    from .vcf import VcfPlugin
  File "/usr/local/lib/python2.7/dist-packages/puzzle/plugins/vcf/__init__.py", line 2, in <module>
    from .vcf import VcfPlugin
  File "/usr/local/lib/python2.7/dist-packages/puzzle/plugins/vcf/vcf.py", line 5, in <module>
    from path import path
ImportError: cannot import name path

**Comment by DamianSkrzypczak** [comment]
Hi, temporary solution is to downgrade path version by using:
`pip install path.py==7.7.1`
Issue comes from changes done so far in path library
