### ISSUE TITLE
Consequence filtering failing with gemini adapter

### ISSUE THREAD

**Issue by vasiliosz** [robinandeer/puzzle#94]
(Sorry about positing a bunch of these - finally have time to test some things) 

Gemini variants load nicely. Frequency filtering and gene list filtering work well. Very nice work!

But not consequence filtering, see below.

Also - to avoid adding lots of terms for filtering effects, in gemini we often use the LOW, MEDIUM, HIGH impact categories as summary terms (`impact_severity`). There is a detailed listing of `impact_severity` vs `impacts` vs `SO_impacts` here: http://gemini.readthedocs.org/en/latest/content/database_schema.html#details-of-the-impact-and-impact-severity-columns

```
[2016-02-04 09:15:58,769] ERROR in app: Exception on /variants/famall7 [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1882, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1537, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1441, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1535, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1521, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vaszac/proj/puzzle/puzzle/blueprints/variants/views.py", line 40, in variants
    return render_template('variants.html', **kwargs)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 123, in render_template
    context, ctx.app)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 105, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vaszac/proj/puzzle/puzzle/blueprints/variants/templates/variants.html", line 3, in top-level template code
    {% from "macros/filters.html" import filters_form %}
  File "/Users/vaszac/proj/puzzle/puzzle/templates/layouts/base.html", line 30, in top-level template code
    {% block body %}
  File "/Users/vaszac/proj/puzzle/puzzle/templates/layouts/base.html", line 47, in block "body"
    {% block body_content %}{% endblock %}
  File "/Users/vaszac/proj/puzzle/puzzle/blueprints/variants/templates/variants.html", line 36, in block "body_content"
    {% for variant in variants %}
  File "/Users/vaszac/proj/puzzle/puzzle/plugins/gemini/variant_mixin.py", line 84, in variants
    if transcript['Consequence'] in consequences:
KeyError: 'Consequence'
```

**Comment by moonso** [comment]
Ok I know why this is happening, will fix asap

**Comment by moonso** [comment]
This is somehow related to #28 . I'm working on a branch to add this filter
