### ISSUE TITLE
PED requirements too conservative?

### ISSUE THREAD

**Issue by vasiliosz** [robinandeer/puzzle#99]
I think the PED requirements are a bit too strict. 
We often use >6 columns to add additional phenotype info - as this can be used for filtering variants in gemini in larger families/cohorts. 

Can ped_parser just ignore additional columns instead of throwing an error?

```
[2016-02-04 12:02:46,304] ped_parser.parser         ERROR    WRONG FORMATED PED LINE!
[2016-02-04 12:02:46,304] ped_parser.parser         INFO     Ped line: famall7	P24xx_103	P24xx_102	P24xx_101	2	2	1	xxxxD	"pat	germline"
Traceback (most recent call last):
  File "/usr/local/bin/puzzle", line 9, in <module>
    load_entry_point('puzzle==0.0.1', 'console_scripts', 'puzzle')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/vaszac/proj/puzzle/puzzle/cli.py", line 142, in load
    vtype=variant_type
  File "/Users/vaszac/proj/puzzle/puzzle/plugins/vcf/vcf.py", line 59, in __init__
    case_type=case_type
  File "/Users/vaszac/proj/puzzle/puzzle/utils/ped.py", line 28, in get_case
    case_type=case_type,
  File "/Users/vaszac/proj/puzzle/puzzle/utils/ped.py", line 66, in get_individuals
    family_parser = FamilyParser(case_lines, family_type=case_type)
  File "/usr/local/lib/python2.7/site-packages/ped_parser/parser.py", line 117, in __init__
    self.ped_parser(family_info)
  File "/usr/local/lib/python2.7/site-packages/ped_parser/parser.py", line 228, in ped_parser
    raise e
ped_parser.exceptions.WrongLineFormat: WRONG FORMATED PED LINE!
```

**Comment by moonso** [comment]
You can use the flag 
```--family_type alt``` in this case

**Comment by vasiliosz** [comment]
:+1:
